name: self_help
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.6.0-266.0.dev
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  logger: ^2.5.0
  shared_preferences: ^2.3.5
  pulsator: ^1.0.0+2
  avatar_glow: ^3.0.1
  glowy_borders: ^1.0.2
  animate_gradient: ^0.0.3
  flutter_localizations:
    sdk: flutter
  intl: any
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.6.1
  mesh_gradient: ^1.3.8
  mesh: ^0.4.2
  flutter_svg: ^2.0.17
  # firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0
  firebase_ui_auth: ^1.16.0
  firebase_dynamic_links: ^6.0.11
  go_router: ^14.6.3
  google_sign_in: ^6.2.2
  community_material_icon: ^5.9.55
  sleek_circular_slider: ^2.0.1
  rxdart: ^0.28.0
  json_annotation: ^4.9.0
  animations: ^2.0.11
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  animated_background: ^2.0.0
  dynamic_background: ^0.5.0
  blurrycontainer: ^2.1.0
  glass_kit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4
  json_serializable: ^6.9.2
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/self_help_icon.png"
  adaptive_icon_foreground: "#e6e7f0"
  adaptive_icon_background: "assets/icons/self_help_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/faces/
    - .env

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/static/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/static/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/Rubik/static/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/static/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/static/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/static/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/static/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik/static/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/static/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
