// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVr9gZT7uNgQR_-tUorrJAzMhqwdutZ5o',
    appId: '1:624248236630:web:b52f6e7d9d4832ddb5e9f7',
    messagingSenderId: '624248236630',
    projectId: 'self-help-47fae',
    authDomain: 'self-help-47fae.firebaseapp.com',
    storageBucket: 'self-help-47fae.firebasestorage.app',
    measurementId: 'G-GY49D29MM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWO6Mf9Fl1fJm-FNSd-jrRpevuYkE3iKc',
    appId: '1:624248236630:android:344edda32f7d924eb5e9f7',
    messagingSenderId: '624248236630',
    projectId: 'self-help-47fae',
    storageBucket: 'self-help-47fae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6F-K97i_EtfJenmUYIIm0SFWKitPG18',
    appId: '1:624248236630:ios:238018813cd248d3b5e9f7',
    messagingSenderId: '624248236630',
    projectId: 'self-help-47fae',
    storageBucket: 'self-help-47fae.firebasestorage.app',
    iosBundleId: 'com.example.selfHelp',
  );

}